In [5]:
import numpy as np
ar=np.array([1,2,3])
ar

array([1, 2, 3])

# Array 

In [19]:
ar=np.array([[1,2,3], [4,5,6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
ar=np.array([1,2,3],dtype=float)
ar

array([1., 2., 3.])

In [21]:
ar=np.array([1,2,3],dtype=complex)
ar

array([1.+0.j, 2.+0.j, 3.+0.j])

In [22]:
ar=np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Arange

In [23]:
ar=np.arange(3)
ar

array([0, 1, 2])

In [24]:
ar=np.arange(1,10,2)
ar

array([1, 3, 5, 7, 9])

# zeros

In [25]:
ar=np.zeros(5)
ar

array([0., 0., 0., 0., 0.])

In [26]:
ar=np.zeros((2,3))
ar

array([[0., 0., 0.],
       [0., 0., 0.]])

# #ones

In [27]:
ar=np.ones(4)
ar

array([1., 1., 1., 1.])

In [30]:
ar=np.ones((2,3))
ar

array([[1., 1., 1.],
       [1., 1., 1.]])

# empty

In [31]:
ar=np.empty(2)
ar

array([0., 0.])

In [32]:
ar=np.empty((2,3))
ar

array([[1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [33]:
ar=np.linspace(1,100)
ar

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [34]:
ar=np.linspace(1,100,num=5)
ar

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [35]:
ar=np.linspace(1,100,num=5,endpoint=False)
ar

array([ 1. , 20.8, 40.6, 60.4, 80.2])

In [36]:
ar=np.linspace(1,100,num=4,retstep=True)
ar

(array([  1.,  34.,  67., 100.]), 33.0)

# random

In [39]:
ar=np.random.rand(5)
ar

array([0.11778449, 0.24924504, 0.50769036, 0.00092393, 0.0327558 ])

In [40]:
ar=np.random.randn(5)
ar

array([ 0.87755447, -1.61561583, -0.05160693,  0.12890024,  1.33120306])

In [44]:
ar=np.random.ranf((5,2))
ar

array([[0.67942927, 0.55206055],
       [0.16706804, 0.75502098],
       [0.21204616, 0.74399417],
       [0.8927622 , 0.61778774],
       [0.07752726, 0.51133672]])